Algoritmo " Temperatura "
// Disciplina   : PA
// Professora :Edilma
// Data atual  : 25/05/2023
// luana garcia mathias
Var
temperatura: real


 //ENTRADA
Inicio
escreval ("Informe a temperatura ")
leia (temperatura)

 // PROCESSAMENTO E SAÍDA

se temperatura < 20 entao
escreval (" Está frio")
senao
se temperatura < 25 entao
escreval(" Normal")
senao
escreval ("Está quente")
fimse
Fimalgoritmo
