Algoritmo "Maior ou menor de idade "
// Disciplina   : PA
// Professora :Edilma
// Data atual  : 25/05/2023
// luana garcia mathias
Var
nome, idade : real


 //ENTRADA
Inicio
escreval ("informe a sua idade")
leia (idade)
escreval ("Informe o seu nome")
leia (nome)


 // PROCESSAMENTO E SAÍDA
se idade >= 18 entao
escreval (nome,"maior de idade")
senao
escreval ( nome, "Menor de idade")
fimse
Fimalgoritmo